assignment4
BCSDLab-Android-Beginner-22-1/BCSD-Beginner-MinGu-Jeong pull request #1
Opened 2022-05-01 17:00 UTC by MinGu-Jeong

현재 다음과 같이 컴파일러에서는 에러가 발생하지는 않으나 앱이 실행되지 않아 제대로 코드를 짠 건지 확인이 불가능합니다.
![error_stop](https://user-images.githubusercontent.com/51395707/166156229-94dbebf3-6898-4607-b61a-d7b5c786b68e.png)

어떤 부분에 오류가 있는지 알려주시면 수정하겠습니다.

2022-05-02 09:09 UTC, KWY0218 commented
앱을 실행하고, 앱이 실행되지 않는 이유가 안드로이드 스튜디오 하단에 있는 Logcat에 나올 거에요!!!
Logcat에 나온 오류들을 구글링해서 한번 알아 보시고, 그래도 모르겠다면 Logcat에 나온 에러들을 댓글로 달아주실래요???

2022-05-02 13:58 UTC, MinGu-Jeong commented
Logcat에서 processes가 잡히지 않는 버그가 있어서 안드로이드스튜디오 업데이트 이후 정상적으로 출력됩니다. 
Log 확인 후 수정하겠습니다.

2022-05-02 15:04 UTC, MinGu-Jeong commented
오류 수정했고, Toast 메시지, Count, Random 모두 잘 작동하지만 한가지 문제가 있습니다.
Random버튼을 눌러 두번째 레이아웃으로 넘어갈때는 인수가 잘 넘어가지만,
두번째 레이아웃에서 뒤로가기를 눌러 첫번째 레이아웃으로 넘어갈때는 인수가 넘어가지않고 getIntExtra의 defaultValue만 들어가는 문제가 있습니다. 
분명 똑같은 구조로 코드를 구현했는데 첫번째에서 두번째로 갈때는 잘되지만, 두번째에서 첫번째로 갈때 되지않는 이유를 모르겠습니다.

2022-05-02 15:06 UTC, Yang-Seungmin commented on app/src/main/java/com/example/myapplication/MainActivity.kt
> +            countNumEditable.text=countNum.toString()
코드 컨벤션 지켜주세요.

2022-05-02 15:13 UTC, Yang-Seungmin requested changes
`두번째 Activity에서 뒤로가기 버튼으로 액티비티를 종료하면 기존 액티비티의 숫자를 두 번째 액티비티의 숫자로 변경` 이 구현되지 않은 것 같네요. 다음주까지 꼭 구현 부탁드립니다

2022-05-02 15:16 UTC, KWY0218 commented
힌트를 드리자면 registerForActivityResult에 대해 다시 공부를 해보면 해결될 것이라고 생각 됩니다!

2022-05-02 15:25 UTC, MinGu-Jeong commented on app/src/main/java/com/example/myapplication/MainActivity.kt
> +            countNumEditable.text=countNum.toString()
죄송하지만 정확히 어느 부분이 잘못 된 건지 잘 모르겠습니다. 변수 선언이 잘못 된 건가요?

2022-05-07 06:34 UTC, MinGu-Jeong commented
1. 두번째 액티비티에서 랜덤값을 첫번째 액티비티로 가져오도록 수정했습니다.
2. 코드 컨벤션의 경우 정확히 어느부분을 어떻게 수정해야되는지 잘 모르겠습니다.

2024-01-07 08:06 UTC, closed without merging